# Generated by Django 6.0 on 2025-12-05 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_blacklist'),
        ('events', '0003_auto_20251205_1255'),
    ]

    operations = [
    ]
