# Generated by Django 6.0 on 2025-12-05 15:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_merge_0002_blacklist_0003_auto_20251205_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Validasi Admin'), ('active', 'Aktif / Tayang'), ('finished', 'Selesai / Terlaksana'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
